import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

let config;

if (process.env.AWS_EXPORTS_JSON) {
    try {
        config = JSON.parse(process.env.AWS_EXPORTS_JSON);
        console.log('✅ Loaded config from AWS_EXPORTS_JSON');
    } catch (e) {
        console.error('❌ Failed to parse AWS_EXPORTS_JSON:', e);
        process.exit(1);
    }
} else {
    config = {
        aws_project_region: process.env.VITE_REGION || 'us-east-1',
        aws_cognito_identity_pool_id: process.env.VITE_IDENTITY_POOL_ID,
        aws_cognito_region: process.env.VITE_REGION || 'us-east-1',
        aws_user_pools_id: process.env.VITE_USER_POOL_ID,
        aws_user_pools_web_client_id: process.env.VITE_USER_POOL_CLIENT_ID,
        oauth: {},
        aws_appsync_graphqlEndpoint: process.env.VITE_API_URL,
        aws_appsync_region: process.env.VITE_REGION || 'us-east-1',
        aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS"
    };
}

const fileContent = `/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by scripts/generate-config.js.
// It will be overwritten during the build process.

const awsmobile = ${JSON.stringify(config, null, 2)};

export default awsmobile;
`;

const outputPath = path.join(__dirname, '../src/aws-exports.js');

fs.writeFileSync(outputPath, fileContent);

console.log('✅ Generated src/aws-exports.js');
console.log(config);