import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const outputPath = path.join(__dirname, '../src/aws-exports.js');

// Only generate when AWS_EXPORTS_JSON is set (CI/CD deployment)
// Otherwise, use the existing aws-exports.js file
if (!process.env.AWS_EXPORTS_JSON) {
    if (fs.existsSync(outputPath)) {
        console.log('✅ Using existing src/aws-exports.js (no AWS_EXPORTS_JSON set)');
        process.exit(0);
    } else {
        console.error('❌ No AWS_EXPORTS_JSON set and src/aws-exports.js does not exist.');
        console.error('   Please create src/aws-exports.js manually or set AWS_EXPORTS_JSON for deployment.');
        process.exit(1);
    }
}

let config;

try {
    config = JSON.parse(process.env.AWS_EXPORTS_JSON);
    console.log('✅ Loaded config from AWS_EXPORTS_JSON');
} catch (e) {
    console.error('❌ Failed to parse AWS_EXPORTS_JSON:', e);
    process.exit(1);
}

const fileContent = `/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by scripts/generate-config.js.
// It will be overwritten during the build process.

const awsmobile = ${JSON.stringify(config, null, 2)};

export default awsmobile;
`;

fs.writeFileSync(outputPath, fileContent);

console.log('✅ Generated src/aws-exports.js');
console.log(config);