/**
 * Gemini AI Service Integration
 * 
 * This module provides the interface to Google's Gemini 2.5 Flash model for:
 * 1. Structured generation - Agent outputs with validated JSON schemas
 * 2. Conversational chat - Interactive resume improvement suggestions
 * 
 * Design Decisions:
 * - Uses Gemini 2.5 Flash for optimal balance of speed, quality, and cost
 * - Structured generation ensures type-safe, parseable agent outputs
 * - Low temperature (0.2) for agents ensures consistent, factual responses
 * - Higher temperature (0.4) for chat enables more creative suggestions
 * - Mock mode allows development/testing without API calls
 */

import { GoogleGenAI, Type } from "@google/genai";
import type { AnalysisResult, ChatMessage } from '../types';
import { log } from './logger';

// API key resolution: Vite env vars take precedence, fallback to Node env
const API_KEY =
  (typeof import.meta !== 'undefined' && (import.meta as any).env?.VITE_GEMINI_API_KEY) ||
  process.env.GEMINI_API_KEY ||
  process.env.API_KEY;

if (!API_KEY) {
  throw new Error("GEMINI_API_KEY / API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

// Mock mode for development/testing without consuming API quota
const MOCK_ENABLED =
  (typeof import.meta !== 'undefined' && (import.meta as any).env?.VITE_GEMINI_MOCK === 'true') ||
  process.env.GEMINI_MOCK === 'true';

type Schema = any; // Gemini schema type (simplified for brevity)

/**
 * Generates structured JSON output from Gemini using a defined schema.
 * 
 * This is the core function used by all agents to ensure type-safe, validated outputs.
 * The schema parameter enforces response structure, preventing hallucinated fields.
 * 
 * @param prompt - The instruction/context for the LLM
 * @param schema - JSON schema defining expected response structure
 * @param temperature - Randomness (0.0 = deterministic, 1.0 = creative). Agents use 0.2 for consistency.
 * @param mockResponse - Optional mock data for testing without API calls
 * @returns Parsed, type-safe response matching the schema
 * 
 * Design Decision: Low temperature for agents
 * - Agents need consistent, factual outputs (not creative writing)
 * - Temperature 0.2 reduces hallucination and improves reliability
 * - Chat uses higher temperature (0.4) for more helpful suggestions
 */
async function generateStructured<T>(prompt: string, schema: Schema, temperature = 0.2, mockResponse?: T): Promise<T> {
  log({ level: 'debug', message: 'Gemini request', extra: { temperature } });
  if (MOCK_ENABLED && mockResponse) {
    return mockResponse;
  }

  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash",
    contents: prompt,
    config: {
      responseMimeType: "application/json", // Force JSON output
      responseSchema: schema, // Validate against schema
      temperature,
    },
  });

  const jsonText = response.text.trim();
  try {
    return JSON.parse(jsonText) as T;
  } catch (err) {
    log({ level: 'error', message: 'Failed to parse Gemini response', error: err, extra: { jsonText } });
    throw err;
  }
}

export { generateStructured, Type };

/**
 * Interactive chat interface with context-aware resume assistance.
 * 
 * Provides conversational AI that understands the full analysis context:
 * - Original resume and its ATS score
 * - Optimized resume generated by the pipeline
 * - Job description requirements
 * - Keyword gaps and suggestions
 * 
 * @param messages - Conversation history (user + assistant messages)
 * @param analysisContext - Complete analysis result for context injection
 * @param currentResumeText - User's current resume (may differ from original if manually edited)
 * @param jobDescriptionText - Target job description
 * @returns AI-generated response with resume improvement suggestions
 * 
 * Design Decision: Comprehensive context injection
 * - Chat receives BOTH original and optimized resumes for comparison
 * - Explicit instructions prevent confusion between original vs optimized scores
 * - Special "UPDATED_RESUME:" marker enables AI to return modified resume text
 * - Detailed scoring criteria (40% keywords, 30% skills, 20% experience, 10% format)
 *   ensures consistent evaluation methodology
 */
export async function chatWithGemini(
  messages: ChatMessage[],
  analysisContext: AnalysisResult | null = null,
  currentResumeText: string = '',
  jobDescriptionText: string = ''
): Promise<string> {
  let systemPrefix = '';

  if (analysisContext) {
    const summary = analysisContext.scoring.output?.alignmentNotes ?? 'Not available';
    const overall = analysisContext.scoring.output?.overall;
    const matching = analysisContext.keywordAnalysis.output?.matchingKeywords?.join(', ') || 'None';
    const missing = analysisContext.keywordAnalysis.output?.missingKeywords?.join(', ') || 'None';
    const suggestions = analysisContext.keywordAnalysis.output?.suggestions?.join('\n- ') || 'None';
    const optimized = analysisContext.optimiser.output?.markdown || '';
    const currentDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

    // Context injection: Provide full analysis context to enable intelligent responses
    systemPrefix = `CURRENT DATE: ${currentDate}

CONTEXT ANALYSIS:
- Original Resume ATS Score: ${overall ?? 'N/A'}/100
- Alignment Summary: ${summary}
- Matching Keywords from Original: ${matching}
- Missing Keywords from Original: ${missing}
- Improvement Suggestions:
- ${suggestions}

OPTIMIZED RESUME (AI-Generated Improved Version):
${optimized}

ORIGINAL RESUME (User's Current Version):
${currentResumeText}

JOB DESCRIPTION:
${jobDescriptionText}

IMPORTANT INSTRUCTIONS:
1. The ATS score of ${overall ?? 'N/A'}/100 applies ONLY to the ORIGINAL resume.
2. The OPTIMIZED resume has been rewritten to address the missing keywords and gaps.
3. When asked to compare, score, or analyze the optimized resume against the job description, you MUST:
   a) Perform a fresh ATS analysis of the OPTIMIZED resume against the job description
   b) Count how many keywords from the job description appear in the optimized resume
   c) Evaluate alignment with job requirements, skills, and experience
   d) Provide a NEW ATS score (0-100) for the optimized resume with detailed justification
   e) Compare this new score to the original score of ${overall ?? 'N/A'}/100
   f) Explain specifically which improvements (added keywords, better alignment, etc.) led to the score change
4. Your scoring should follow these criteria:
   - Keyword match rate (40%): How many JD keywords appear in the resume
   - Skills alignment (30%): How well skills match the requirements
   - Experience relevance (20%): How relevant is the experience to the role
   - Format & clarity (10%): ATS-friendly formatting and clear presentation
5. If the user asks you to modify their resume, respond with your explanation followed by "UPDATED_RESUME:" and then the complete updated resume text.
6. Always be specific and reference actual content from the resumes and job description.`;
  }

  const conversation = messages.map(m => `${m.role.toUpperCase()}: ${m.content}`).join('\n\n');
  const prompt = `${systemPrefix}\n\nYou are an expert resume assistant. Continue the conversation below and provide a helpful, concise reply that uses the analysis context above when relevant.\n\n${conversation}\n\nASSISTANT:`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: { temperature: 0.4 }, // Higher temperature for more creative/helpful suggestions
    });

    return response.text.trim();
  } catch (err) {
    console.error('Gemini chat error:', err);
    throw new Error('Failed to get chat response from Gemini.');
  }
}
