import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const targetPath = path.join(__dirname, '../src/aws-exports.js');

// Only generate if the environment variable exists
if (process.env.AWS_EXPORTS_JSON) {
    try {
        const config = process.env.AWS_EXPORTS_JSON;
        const fileContent = `/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by Vercel build script.

const awsmobile = ${config};

export default awsmobile;
`;

        fs.writeFileSync(targetPath, fileContent);
        console.log('[Vercel] Successfully generated src/aws-exports.js from environment variable.');
    } catch (error) {
        console.error('[Vercel] Error generating aws-exports.js:', error);
        process.exit(1);
    }
} else {
    console.log('[Vercel] AWS_EXPORTS_JSON not found. Skipping aws-exports.js generation (assuming local dev or file exists).');
}